version: "3.9"

networks:
  infra:
    name: infra

services:
  pg:
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p1ssw0rd
    ports:
      - '54320:5432'
    volumes: 
      - /infra/pg/data:/var/lib/postgresql/data

  # 服务器顶不住，emmm,再说
  # gitlab:
  #   image: 'gitlab/gitlab-ee:latest'
  #   restart: always
  #   # hostname: 'gitlab.example.com'
  #   # environment:
  #   #   GITLAB_OMNIBUS_CONFIG: |
  #       # external_url 'https://gitlab.example.com'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   ports:
  #     - '8100:80'
  #     - '443:443'
  #     - '23:22'
  #   volumes:
  #     - '/infra/gitlab/config:/etc/gitlab'
  #     - '/infra/gitlab/logs:/var/log/gitlab'
  #     - '/infra/gitlab/data:/var/opt/gitlab'
  #   shm_size: '256m'

