version: "3.9"

networks:
  infra:
    name: infra

services:
  pg:
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p1ssw0rd
    ports:
      - '54320:5432'
    volumes: 
      - /infra/pg/data:/var/lib/postgresql/data

