version: "3.9"

networks:
  infra:
    name: infra

services:
  pg:
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p1ssw0rd
    ports:
      - '54320:5432'
    volumes: 
      - /infra/pg/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8200:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: slient@slient.com
      PGADMIN_DEFAULT_PASSWORD: p1ssw0rd
    volumes:
      - /infra/pg/admin:/var/lib/pgadmin

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 63790:6379
    privileged: true
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - /infra/redis/data:/data
      - /infra/redis/conf/redis.conf:/etc/redis/redis.conf
  pulsar:
    image: apachepulsar/pulsar
    hostname: pulsar
    restart: always
    environment:
      PULSAR_MEM: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g"
      BOOKIE_MEM: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g"
    ports:
      - "6650:6650"
      - "6080:8080"
    volumes:
      - "/infra/pulsar/data:/pulsar/data"
    command: bin/pulsar standalone
  pulsar-manager:
    image: apachepulsar/pulsar-manager
    restart: always
    depends_on:
      - pulsar
    links:
      - pulsar
    # environment:
      # SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    ports:
      - "9527:9527"
      - "7750:7750"
    volumes:
      # - "/infra/pulsar/manager/config/pulsar/application.properties:/pulsar-manager/pulsar-manager/application.properties"
      - "/infra/pulsar/manager/dbdata:/pulsar-manager/pulsar-manager/dbdata"

  # 服务器顶不住，emmm,再说
  # gitlab:
  #   image: 'gitlab/gitlab-ee:latest'
  #   restart: always
  #   # hostname: 'gitlab.example.com'
  #   # environment:
  #   #   GITLAB_OMNIBUS_CONFIG: |
  #       # external_url 'https://gitlab.example.com'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   ports:
  #     - '8100:80'
  #     - '443:443'
  #     - '23:22'
  #   volumes:
  #     - '/infra/gitlab/config:/etc/gitlab'
  #     - '/infra/gitlab/logs:/var/log/gitlab'
  #     - '/infra/gitlab/data:/var/opt/gitlab'
  #   shm_size: '256m'

